version: '2'
services:
    summa-app:
        image: summa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://summa-mysql:3306/summa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    summa-mysql:
        extends:
            file: mysql.yml
            service: summa-mysql
